name: 'Verdaccio Publish Action v2'
description: 'This action will deploy your package to Verdaccio Registry'
author: 'GitHub'
inputs:
  cli:
    description: 'npm command to use'
    default: 'publish'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.cli }}
